### ISSUE TITLE
Missing test data

### ISSUE THREAD

**Issue by akskuchi** [adobe-research/aesop#1]
Hello,

`data/test.json` file comprises only a single sample repeating 1000 times. 
Please fix this.

Regards,
Adi

**Comment by Hareesh-Ravi** [comment]
Thank you for pointing this out @akskuchi . We are fixing it.

**Comment by Hareesh-Ravi** [comment]
@akskuchi :
Please use the updated data at https://github.com/adobe-research/aesop/releases/tag/v1.0
Let us know if there are any other concerns.
